#!/usr/bin/env bash

if [ ! -d "$WORK_DIR" ]; then
    echo "ERROR: Work Directory ($WORK_DIR) does not exist."
fi

# use winpty for interactive terminal commands on windows MINGW
winpty=""
if [[ $(uname) =~ MINGW* ]]; then
    winpty="winpty "
fi

alias ls='ls --color=auto'
alias grep='grep --color=auto'

# must run in current instance, cannot be independent
wd () { cd $WORK_DIR/$1 && ls --color=auto; }

if [ "$HAS_PYTHON" == true ]; then
    alias python="${winpty}python3"
    alias pip="${winpty}pip3"
    alias pip-upgrade="${winpty}python -m pip install --upgrade pip"
fi

if [ "$HAS_DOCKER" == true ]; then
    alias dc="docker-compose"
    alias dcr="${winpty}docker-compose run --rm"
    alias dex="${winpty}docker exec -it"
    alias dxx="docker system prune --all --volumes --force"
    dkc () { docker kill $(docker ps -q); }
fi

alias git-log="git log --format='%C(auto)%h %s %Cgreen<%aN> %Cred(%cr)' -n 10"
alias git-update="git pull --rebase --prune origin && git submodule update --init --recursive"
alias git-publish="git push -u origin HEAD"
alias git-undo="git reset --mixed HEAD~"
