#!/usr/bin/env bash
set -euo pipefail

echo ">> Checking configs file <<"
if [ ! -f "./configs.sh" ]; then
    echo "No configs file found, creating..."
    cp configs_template.sh configs.sh
    vi configs.sh
fi

source ./configs.sh

echo "Work Dir: $WORK_DIR"
echo "Docker:   $HAS_DOCKER"
echo "Python:   $HAS_PYTHON"

echo ">> Creating .bashrc <<"
sed -e "s~INSERT_BASE_DIR~$(pwd)~" bashrc_template.sh > ~/.bashrc

echo "=> Restart terminal to load changes."
