#!/usr/bin/env bash

set -e
set -u 
set -o pipefail

echo ">> Checking configs file <<"
if [ ! -f "./configs" ]; then
    echo "No configs file found, creating..."
    cp configs_template configs
    vi configs
fi

source ./configs

if [ ! -d "$WORK_DIR" ]; then
    echo "ERROR: Work Directory ($WORK_DIR) does not exist."
    exit 1
fi

echo "Work Dir: $WORK_DIR"
echo "Docker:   $HAS_DOCKER"
echo "Python:   $HAS_PYTHON"

echo ">> Creating .bashrc <<"
sed -e "s~INSERT_BASE_DIR~${PWD}~" bashrc_template > ~/.bashrc

echo "Load .bashrc using \"source ~/.bashrc\" or by restarting terminal."

exit 0
