#!/usr/bin/env bash
set -euo pipefail

usage () {
    echo "git-publish [-f]"
    echo "  Confirm commits and push."
    echo "Flags:"
    echo "  -f : Force push"
}

if [ ! -d ".git" ]; then
    echo "ERROR: Not a git repo."
    exit 1
fi

do_force=false
while getopts ":fh" opt; do
    case "$opt" in
        "f")
            do_force=true
            ;;
        "h")
            usage
            exit 1
            ;;
        *)
            echo "ERROR: Invalid argument"
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND -1))

git fetch origin

echo ">> Confirm commits to push <<"
git-log origin/HEAD..HEAD

cur_branch=$(git rev-parse --abbrev-ref HEAD)
echo -n "Publish the above commits to $cur_branch (y/n)? "
read reply

if [[ ${reply,,} =~ ^(y|yes)$ ]]; then
    echo ">> Pushing changes <<"
    flags="-u"
    if [ "$do_force" == true ];then
        echo "Setting force push flag."
        flags="${flags}f"
    fi
    git push $flags origin HEAD

    echo "done."
    exit 0
fi

echo "=> Publish cancelled, no changes have been made."
