#!/usr/bin/env bash
set -euo pipefail

if [ ! -d ".git" ]; then
    echo "ERROR: Not a git repo."
    exit 1
fi

git fetch origin
cur_branch=$(git rev-parse --abbrev-ref HEAD)
base_commit=$(git merge-base origin/$cur_branch $cur_branch)

echo ">> Confirm commits to pull <<"
git-log HEAD..$base_commit

echo -n "Pull the above commits to $cur_branch (y/n)? "
read reply

if [[ ${reply,,} =~ ^(y|yes)$ ]]; then
    echo ">> Pulling changes <<"
    git stash --quiet
    git pull --rebase --prune origin
    if [ -n "$(git stash list)" ]; then
        git stash pop
    fi

    echo "done."
    exit 0
fi

echo "=> Update cancelled, no changes have been made."
