#!/usr/bin/env bash
set -euo pipefail

if [ ! -d ".git" ]; then
    echo "ERROR: Not a git repo."
    exit 1
fi

echo ">> Confirm commits to reset <<"
git fetch origin --quiet
cur_branch=$(git rev-parse --abbrev-ref HEAD)
base_commit=$(git merge-base origin/$cur_branch $cur_branch)
git-log $base_commit..HEAD

echo -n "Reset $cur_branch on remote, this throw away the above commits (y/n)? "
read reply

if [[ ${reply,,} =~ ^(y|yes)$ ]]; then
    echo ">> Resetting on origin/$cur_branch <<"
    git reset --hard origin/$cur_branch
    git clean -fd
    exit 0
fi

echo "=> Reset cancelled, no changes have been made."
