#!/usr/bin/env bash

set -e
set -u 
set -o pipefail

usage () {
    echo "Copies source directory to a new directory and removes .git from new location."
    echo "  np [source] [destination]"
}

# options
while getopts ":h" opt; do
    case "$opt" in
        h)
            usage
            exit 0
            ;;
        ?)
            echo "ERROR: Invalid flag"
            exit 1
            ;;
    esac
done

# errors
if [ -z "${2+x}" ]; then
    echo "ERROR: Missing arguments."
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "ERROR: Source directory does not exist."
    exit 1
fi

if [ -d "$2" ]; then
    echo "ERROR: Destination directory already exists."
    exit 1
fi

#exec
echo "Copying $1 to $2..."
cp $1 $2 -r
cd $2

if [ -d ".git" ]; then
    echo "Removing .git from $2..."
    rm -rf .git
fi

echo "Done."
exit 0
