#!/usr/bin/env bash
set -euo pipefail

if [ -z "${2+x}" ]; then
    echo "ERROR: Missing arguments."
    exit 1
fi

src_dir="$1"
dest_dir="$2"

if [ ! -d "$src_dir" ]; then
    echo "ERROR: Source directory does not exist."
    exit 1
fi

if [ -d "$dest_dir" ]; then
    echo "ERROR: Destination directory already exists."
    exit 1
fi

echo "Copying $src_dir to $dest_dir..."
cp $src_dir $dest_dir -r
cd $dest_dir

if [ -d ".git" ]; then
    echo "Reset git in $dest_dir..."
    rm -rf .git
    git init
fi

echo "=> New project created at ./$dest_dir"
